### ISSUE TITLE
fxr launch doesn't work on windows.

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/fxr-cli#22]
fxr doesn't work in windows linux due to not being able to see the Go:
![image](https://user-images.githubusercontent.com/1560884/42788758-3eca3858-8916-11e8-860d-c356112ebe02.png)

seems that this due to a lack of USB support in WSL: https://github.com/Microsoft/WSL/issues/2195

device is seen in windows power shell though, so i decided to install fxr using just standard windows cli:

![image](https://user-images.githubusercontent.com/1560884/42788283-843ae584-8913-11e8-93d9-3c7b960b1ee6.png)

installing fxr in windows works, but I get an error when running `fxr launch`

![image](https://user-images.githubusercontent.com/1560884/42788350-e27373f0-8913-11e8-91fd-8461a99659af.png)

Looking at some of the options in the WSL issue (ie running adb-server on windows, accessing over network)

**Comment by caseyyee** [comment]
OK update here, a dumb hack.

Need to run adb-server on windows:

![image](https://user-images.githubusercontent.com/1560884/42788973-7aaa8156-8917-11e8-9ad0-f6ea73a058be.png)

and within WSL, you can see devices and run fxr-cli:

![image](https://user-images.githubusercontent.com/1560884/42788999-977e73fa-8917-11e8-8be4-2e1e06f3dc51.png)

**Comment by cvan** [comment]
whoa, weird. thanks for filing and for investigating. not sure if it's the same error (yours looks a bit different), but it could be similar to [this Windows permissions error](https://github.com/jamie-sherriff/android-platform-tools#troubleshooting) documented in the `adb` wrapper package I'm using ([`android-platform-tools`](https://www.npmjs.com/package/android-platform-tools)).

I have a local branch that I think fixes this. I'll comment in this issue and file a follow-up PR for you to test. in the meantime, I'll test on my Windows machine.

thanks for filing, @caseyyee!
