### ISSUE TITLE
add `fxr capture` for video screencaptures and screenshots

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/fxr-cli#29]
Maybe `fxr screencapture`?

Instructions as per slack are pretty clunky, being wrapped up with the fxr-cli would make things much easier:

manuel.martin [9:44 AM]
adb shell screencap -p /sdcard/1.png

for video: adb shell setprop debug.oculus.enableVideoCapture 1 and adb shell setprop debug.oculus.enableVideoCapture 0 when finished (edited)
adb pull /sdcard/oculus/VideoShots/X ./X for grabbing them

**Comment by cvan** [comment]
thanks for filing! this is very useful.

this is the next addition I plan on making to the CLI :+1: I've got a [WIP branch](https://github.com/MozillaReality/fxr-cli/compare/master...cvan:capture) (not ready yet, doing some refactoring).

it'll be `fxr capture` (with numerous aliases: `fxr screencapture`, `fxr record`, `fxr screenshot`, `fxr screengrab`, `fxr video`, etc.).

it'll handle video capture (using feature detection in #19 to know which method to use: Oculus's [like you posted above], [GoogleVR's](https://github.com/bluemarvin/ascripts/blob/master/gvr-record.sh), [Android's](https://github.com/bluemarvin/ascripts/blob/master/arecord.sh), etc.) and regular screenshots (`adb shell screencap`). and more! 😀
